---
- name: Install PostgreSQL and psycopg2
  package:
    name:
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: true
  notify: Restart postgresql

- name: Start and enable postgresql
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create app database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    state: present
  notify: Restart postgresql

- name: Create app user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    db: "{{ postgres_db }}"
    priv: ALL
    state: present
  notify: Restart postgresql